name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Ant (bootstrap)
        run: ant -noinput -buildfile build.xml bootstrap
      - name: Build with Ant (jar)
        run: ant -noinput -buildfile build.xml jar
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "/home/runner/work/k5z-lang/k5z-lang/dist/k5z.jar"
          token: ${{ secrets.GITHUB_TOKEN }}